name: 'DocTide Action'
description: 'GitHub Action using an LLM agent to auto-generate function-level docs for new or changed functions on user-defined pushes.'
inputs:
  testing:
    description: 'A boolean which sets the workflow to run in test-mode: committing directly instead of opening a pull-request'
    default: false
    required: false
    type: boolean
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.testing }}
branding:
  icon: "file-text"
  color: "blue"
