sprite $DocTide_logo [128x128/16z] {
n5g9TkIg3kpAlAGN8_7_V_i2bEjO1tFLdbNPm2QKL5hGCBdzPi7Lb_Xra5zV--TP07xsb_7RbVddZFoHCC0VrZXVWFLIx0k0twEhTaMIMlWJCO8L4gve_yT3
5hzr2_ojaCARJ269mrGD_7bsjHI_j0rMZxB0Gxv4otBQqJuukcvp3d3T1OYJECxrqXHfJE4tH0QIMSvTNjIm7kVh95bmrUfUQwQjNbuNBBMiriLjICL_yuDh
RaXUlHgoctcpVrVX3pLcY1EPVdzGxe_lOMS2ytR0vSg89CKQ-6CMRpejYxW4IvJyzq3qpzto-xr_9mtk2eD5ZK6I14ZZrSpAewFAS8xkJG6lGTiiGo-oWvkB
UXgkSPyLCvmc7jvoVdR2mim7d0p_yf65PSoF-edrgmST5YveyB9MCMUI-CJDF8N3bJU4aFc-8pdnNkH3Kf4wDvTeVJUyiVrv179-DGBg8DviCwiJUbgfL-_C
dAn_RTy_LN-9NKSTR0xOrp-BMHNsXLeBp3CN-MNRekTLTz26UmgOFrzDBvgBze7B1uuu4VosRVTklOjvhXgbsRtZmEpvUgqOoCC0yRkPoVhjSPVbB_6jOz7u
6mt_PMOrEzEH9y3_p6NzLXv6sJOpYu4TySc03CaEP2oSOFP5-B9jjDxjUsA-IY_YlnWUISmbUM16-2OFMT_CrqB4dTpyjIk0jriYd2h5qtuhfT7lEtmfPfzS
YQdRiLtSpt8GxxVL6EQ_6dWpclXzg0YQr2ZqaXz346_fW3YfxcI_4o3psr3m_9f2213-rVIBqRTH1lrbc6zlzEGT7sBquYK1wFwlCjZVHi7TLJaxtFL3-C35
hZn6aX_CfrktQB_EmIWk-vUxv__agiIdcEWlXVY0BKJuw-XAXCa_o1V_WuhDvV-FZny_Vdn_jPzzs3u-v7-QWem7pH3nxmsjo7vJAdBZvOsOy5UDQKwAcTWd
lkpdrcTD9sByo_QB8ln2o69cJljZ0WWrc2_yax17cWqC_tj7zuOg_pyLW1tZL6hm_-nTPBb7-uVnIdfhHz-hLKCpQ-lMyO-cVpqWljs1Qsn6zpTK5e3U1Z02
kzplzw_x9FB_zNvR_XZufHJXi_my6OtBhG75Vs9Y7CMVC7lIVYQz3mKUJwK0bY54_5Ns8xyyW_aNWHig6u2ENqJ0MkZ_vC8Gq31Q0_HEdjM69v2DqVFPlhiR
29JL_rC2a7KcrPpyqm5zvuOl1j3MVGParNyG7qVCTxf-_JJRyNrJ2IXbAy_dun23CAT8Tlu5m2yazs_nAV5BRtdLWdK7I87F-NuMeVvTlrbM39ZuDmkZSb30
botUel_3-ipG0Fk5boeVJs6cO6U0GMZHmzn4-9djM3_20Tzr2ZS5IcFWAKg0ims5Zul_vIDBp8mOxiu-mFciAS07qc3A_xSxJfmwwaFuFVFKXlSUx14eq7ay
yuzpA2peZqSu8TNw4qyKl1GMLaCB97m4n5KvLEJW-BhGLcFpAH-qS60K5CM8kKc1uFzGS4yVh8xeHZkFFlT1HlzI9_IG1fixcuzFvV-YGRpmd-zcuhTz4Rvz
ypOkfRFmK7fsuMAlzretqfhXWHF4ij0m5G5gG8lqA6DmqCiyd0KH3k-UlneF3xWRETWe3Op20PyM3hh7J5Zo-moFayuK2Wbp8xC-LDWEGlj9GE6OhuBrYRq1
EnJJEWvzCudmclCP2q4A5RRNWbGDDGUMVcdx2D-fWOnMIJ3neQkI-fxra7OX3YK73qW7QK2n4waJpkfALWFDGtis3fq30Tu-f45HZGeaLQn9Fs11HazQQJuw
lx2xAg9uY0hQQvtur_kHsYdlXhi7BTmLVE7vj1rckzQDIMH1FX2e9HBWSOAEzs_XM1z6xX-TF6cZyNssPZcPsT0aHib7OhfBg-bUCZCwB9u7uBmAGPWdMd3n
Ek2N6kK7L9s0FR9lYvX2BFEpIjCFB5XXzWT5DDDAXD49Md8b1KmwwTrdvDyvUlsElsex0YCMob0uKKEb_S0P712dUgJ1XNyGQdtOIzjDW41QrQ9nCdgEZqL0
H7xE0axFysjt26D5GeXVd7SoMFIPxrv4GTokgxBQzOJOjOE5j5WcgAXpj0n1RZ0N0_eVkNVrqyIKKA_0yKaeXwhdDnEWyEUWM47BmkEUKneY76SH7mTyhEqN
dBQBlWw76bSTZGzBZsMm0UejyJbFWZuyQC0Ymf8_yUIoQ0x7v7_2IqhBGENLhZEYsbuL0TFfCPUPfPHUWL7TlFRV0K0_rOYwvcFWAnHrvZadTBksTB7K7u5z
YbarjqEKUfe2K50VF4W4am8moIkkzyOHO0UXFuUaVseIySUOVTUD-mAVvBu_f3hodCitg2I6sxbRbQ7J-G3z8EdQSII4qkqGR_Ie_0Kp9px47kWdxeNqxwMF
zhzs_AhRADnShoF-W0AKjNLNjtOnjydVPms94K34cpb3mscGVb7uKFpTz5xu4YpF0MYk_8C8v_w4xkf8NuXlm6L_cmhV9RYbeloJPNhG8ufA2Jx6F_4B1ZwN
tw7r05OvYEZFvquPlEsuMzfGM7lidF-Hfae7dGAErIaGX-RATcr4yP3_VElC5p3KdyUcdCkzTwohJY36ey1KiY1ro7X_Hxj0bcJmJR_D-YTz8jihPOH_g4u3
NGnMTTkXNksfNZfy9uBBtNGLcD_4pZggbVn_wMQHm30CnC3E_p_TesayXTpANL0M57b-1MIMEj05DNZssdapXzTi2xKwSbLsSeD1huuzq2FFUNOUmbNgX6mW
xFfJaSZ-GvmtdDhyG05xBlWYmFiF1xHpuCL-EQqKKz64s894vWXCfa4BPRwK5l3yo1s7ifoZgL3c0XYct3FuR2xBLKQuNlfs5dlw3x_ahNOB4L06GEEZ61IH
Io1mpLv7IOpIeYrENWAEnP54eBSGVF623vwYt0JPwLgVmDV7Rxvb5NCECz8AMhXB55NX85dmJt0ZN1Y0sInGk21jC9GO4KTnGTsCF8ajpi1jL8zQ0o--cEVw
Ck_dTrq46KXom7Mu4ooPYD9nXtrO2SIsAa-Y_ViTpAPVtm
}